---
- name: Install pre-reqs such as helm
  hosts: localhost
  gather_facts: false
  roles:
    - role: argocd_prereq

- name: Install ArgoCD
  hosts: localhost
  gather_facts: false
  roles:
    - role: argocd
